

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  pull_request:
    branches: 
      - main
      
jobs:
    build:
        name: Call Jenkins Pipeline
        runs-on: self-hosted
        steps:
        - name: Trigger Jenkins Multiple Jobs
          if: github.event.pull_request.merged == true
          uses: appleboy/jenkins-action@v0.0.2
          with:
           url: "137.83.209.141:8080/"
           user: "Jeroen"
           token: ${{ secrets.JENKINS_TOKEN }}
           job: "Test"
          
