

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on:
  pull_request:
    branches: 
      - main
      
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: self-hosted
        steps:
        - name: Azure Pipelines Action
          if: github.event.pull_request.merged == true
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/jeroenbackx/PipelineTest
            azure-pipeline-name: 'PipelineTest-CI'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
